export const GET_INFLUENCER_REQUEST ='GET_INFLUENCER_REQUEST';

export const GET_INFLUENCER_SUCCESS ='GET_INFLUENCER_SUCCESS';

export const GET_INFLUENCER_ERROR ='GET_INFLUENCER_ERROR';



export const GET_SINGLE_INFLUENCER_REQUEST ='GET_SINGLE_INFLUENCER_REQUEST';

export const GET_SINGLE_INFLUENCER_SUCCESS ='GET_SINGLE_INFLUENCER_SUCCESS';

export const GET_SINGLE_INFLUENCER_ERROR ='GET_SINGLE_INFLUENCER_ERROR';



export const CREATE_INFLUENCER_REQUEST ='CREATE_INFLUENCER_REQUEST';

export const CREATE_INFLUENCER_SUCCESS ='CREATE_INFLUENCER_SUCCESS';

export const CREATE_INFLUENCER_ERROR ='CREATE_INFLUENCER_ERROR';


export const EDIT_INFLUENCER_REQUEST ='EDIT_INFLUENCER_REQUEST';

export const EDIT_INFLUENCER_SUCCESS ='EDIT_INFLUENCER_SUCCESS';

export const EDIT_INFLUENCER_ERROR ='EDIT_INFLUENCER_ERROR';


export const DELETE_INFLUENCER_REQUEST ='DELETE_INFLUENCER_REQUEST';

export const DELETE_INFLUENCER_SUCCESS ='DELETE_INFLUENCER_SUCCESS';

export const DELETE_INFLUENCER_ERROR ='DELETE_INFLUENCER_ERROR';