export const GET_INFLUENCER_REQUEST ='GET_INFLUENCER_REQUEST';

export const GET_INFLUENCER_SUCCESS ='GET_INFLUENCER_SUCCESS';

export const GET_INFLUENCER_ERROR ='GET_INFLUENCER_ERROR';



export const GET_SINGLE_INFLUENCER_REQUEST ='GET_SINGLE_INFLUENCER_REQUEST';

export const GET_SINGLE_INFLUENCER_SUCCESS ='GET_SINGLE_INFLUENCER_SUCCESS';

export const GET_SINGLE_INFLUENCER_ERROR ='GET_SINGLE_INFLUENCER_ERROR';