
export const citiesData = [
    {key: 'Cairo', text: 'Cairo', value: 'Cairo'},
    {key: 'Alexandria', text: 'Alexandria', value: 'Alexandria'},
    {key: 'Giza', text: 'Giza', value: 'Giza'},
    {key: 'Shubra el-Khema', text: 'Shubra el-Khema', value: 'Shubra el-Khema'},
    {key: 'Port Said', text: 'Port Said', value: 'Port Said'},
    {key: 'Suez', text: 'Suez', value: 'Suez'},
    {key: 'El Mahalla el Kubra', text: 'El Mahalla el Kubra', value: 'El Mahalla el Kubra'},
    {key: 'El Mansoura', text: 'El Mansoura', value: 'El Mansoura'},
    {key: 'Tanta', text: 'Tanta', value: 'Tanta'},
    {key: 'Asyut', text: 'Asyut', value: 'Asyut'},
    {key: 'Fayoum', text: 'Fayoum', value: 'Fayoum'},
    {key: 'Ismailia', text: 'Ismailia', value: 'Ismailia'},
    {key: 'Khusus', text: 'Khusus', value: 'Khusus'},
    {key: 'Aswan', text: 'Aswan', value: 'Aswan'},
    {key: 'Damanhur', text: 'Damanhur', value: 'Damanhur'},
    {key: 'El-Minya', text: 'El-Minya', value: 'El-Minya'},
    {key: 'Damietta', text: 'Damietta', value: 'Damietta'},
    {key: 'Luxor', text: 'Luxor', value: 'Luxor'},
    {key: 'Qena', text: 'Qena', value: 'Qena'},
    {key: 'Beni Suef', text: 'Beni Suef', value: 'Beni Suef'},
    {key: 'Sohag', text: 'Sohag', value: 'Sohag'},
    {key: 'Hurghada', text: 'Hurghada', value: 'Hurghada'},
    {key: 'Banha', text: 'Banha', value: 'Banha'},
    {key: 'Kafr al-Sheikh', text: 'Kafr al-Sheikh', value: 'Kafr al-Sheikh'},
    {key: 'Marsa Matruh', text: 'Marsa Matruh', value: 'Marsa Matruh'},
    {key: 'Kafr el-Dawwar', text: 'Kafr el-Dawwar', value: 'Kafr el-Dawwar'},
];