export const GET_USER_BY_ID_REQUEST ='GET_USER_BY_ID_REQUEST'

export const GET_USER_BY_ID_SUCCESS ='GET_USER_BY_ID_SUCCESS'

export const GET_USER_BY_ID_ERROR ='GET_USER_BY_ID_ERROR'



export const ADMIN_UPDATE_REQUEST ='ADMIN_UPDATE_REQUEST'

export const ADMIN_UPDATE_SUCCESS ='ADMIN_UPDATE_SUCCESS'

export const ADMIN_UPDATE_ERROR ='ADMIN_UPDATE_ERROR'