
export const GET_USERS_REQUEST ='GET_USERS_REQUEST'

export const GET_USERS_SUCCESS ='GET_USERS_SUCCESS'

export const GET_USERS_ERROR ='GET_USERS_ERROR'


export const EDIT_USERS_REQUEST ='EDIT_USERS_REQUEST'

export const EDIT_USERS_SUCCESS ='EDIT_USERS_SUCCESS'

export const EDIT_USERS_ERROR ='EDIT_USERS_ERROR'


export const DELETE_USERS_REQUEST ='DELETE_USERS_REQUEST'

export const DELETE_USERS_SUCCESS ='DELETE_USERS_SUCCESS'

export const DELETE_USERS_ERROR ='DELETE_USERS_ERROR'


