
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';

export const CREATE_REPORT_REQUEST = 'CREATE_REPORT_REQUEST';

export const CREATE_REPORT_ERROR = 'CREATE_REPORT_ERROR';




export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';

export const GET_REPORT_REQUEST = 'GET_REPORT_REQUEST';

export const GET_REPORT_ERROR = 'GET_REPORT_ERROR';